FROM lung-csp:data

COPY ../keras_csp /root/csp/keras_csp/
WORKDIR /root/csp/keras_csp/
RUN make

WORKDIR /root

COPY ../scripts /root/csp/scripts/

COPY ../train_caltech.py /root/csp/
COPY ../test_caltech.py /root/csp/

COPY ../data/cache/ /root/csp/data/cache/

COPY ../scripts/all.sh /root